#
# Module manifest for module 'PSFalcon'
#
# Generated by: brendan.kremian@crowdstrike.com
#
# Generated on: 1/15/2021
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSFalcon.psm1'

# Version number of this module.
ModuleVersion = '2.0.7'

# Supported PSEditions
CompatiblePSEditions = @('Desktop','Core')

# ID used to uniquely identify this module
GUID = 'd893eb9f-f6bb-4a40-9caf-aaff0e42acd1'

# Author of this module
Author = 'Brendan Kremian'

# Company or vendor of this module
CompanyName = 'CrowdStrike'

# Copyright statement for this module
Copyright = '(c) CrowdStrike. All rights reserved.'

# Description of the functionality provided by this module
Description = "PowerShell for CrowdStrike's OAuth2 APIs"

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the
# PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for
# the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @('Class/Class.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry,
# use an empty array if there are no functions to export.
FunctionsToExport = @(
    # cloud-connect-aws
    'Confirm-DiscoverAwsAccess',
    'Edit-DiscoverAwsAccount',
    'Get-DiscoverAwsAccount',
    'Get-DiscoverAwsSettings',
    'New-DiscoverAwsAccount',
    'Remove-DiscoverAwsAccount',
    'Update-DiscoverAwsSettings',

    # cloud-connect-azure
    'Get-DiscoverAzureAccount',
    'Get-DiscoverAzureScript',
    'New-DiscoverAzureAccount',
    'Update-DiscoverAzureAccount',

    # cloud-connect-cspm-aws
    'Get-HorizonAwsAccount',
    'Get-HorizonAwsLink',
    'New-HorizonAwsAccount',
    'Receive-HorizonAwsScript',
    'Remove-HorizonAwsAccount',

    # cloud-connect-cspm-azure
    'Edit-HorizonAzureAccount',
    'Get-HorizonAzureAccount',
    'New-HorizonAzureAccount',
    'Receive-HorizonAzureScript',
    'Remove-HorizonAzureAccount',

    # cloud-connect-gcp
    'Get-DiscoverGcpAccount',
    'New-DiscoverGcpAccount',
    'Receive-DiscoverGcpScript',

    # config
    'Export-Config',
    'Import-Config',

    # detects
    'Edit-Detection',
    'Get-Detection',

    # devices
    'Add-HostTag',
    'Edit-HostGroup',
    'Get-Host',
    'Get-HostGroup',
    'Get-HostGroupMember',
    'Invoke-HostAction',
    'Invoke-HostGroupAction',
    'New-HostGroup',
    'Remove-HostGroup',
    'Remove-HostTag',

    # falconx
    'Get-Report',
    'Get-Submission',
    'Get-SubmissionQuota',
    'New-Submission',
    'Receive-Artifact',
    'Remove-Report',

    # fwmgr
    'Edit-FirewallGroup',
    'Edit-FirewallSetting',
    'Get-FirewallEvent',
    'Get-FirewallField',
    'Get-FirewallGroup',
    'Get-FirewallPlatform',
    'Get-FirewallRule',
    'Get-FirewallSetting',
    'New-FirewallGroup',
    'Remove-FirewallGroup',

    # incidents
    'Get-Behavior',
    'Get-Incident',
    'Get-Score',
    'Invoke-IncidentAction',

    # indicators
    'Edit-IOC',
    'Get-IOC',
    'Get-IOCHost',
    'Get-IOCProcess',
    'Get-IOCTotal',
    'New-IOC',
    'Remove-IOC',

    # installation-tokens
    'Edit-InstallToken',
    'Get-InstallToken',
    'Get-InstallTokenEvent',
    'Get-InstallTokenSettings',
    'New-InstallToken',
    'Remove-InstallToken',

    # intel
    'Get-Actor',
    'Get-Indicator',
    'Get-Intel',
    'Get-Rule',
    'Receive-Intel',
    'Receive-Rule',

    # ioarules
    'Edit-IOAGroup',
    'Edit-IOARule',
    'Get-IOAGroup',
    'Get-IOAPlatform',
    'Get-IOARule',
    'Get-IOASeverity',
    'Get-IOAType',
    'New-IOAGroup',
    'New-IOARule',
    'Remove-IOAGroup',
    'Remove-IOARule',
    'Test-IOARule',

    # malquery
    'Get-MalQuery',
    'Get-MalQueryQuota',
    'Get-MalQuerySample',
    'Group-MalQuerySample',
    'Invoke-MalQuery',
    'Receive-MalQuerySample',

    # mssp
    "Add-CIDGroupMember",
    "Add-GroupRole",
    "Add-UserGroupMember",
    "Edit-CIDGroup",
    "Edit-UserGroup",
    "Get-CIDGroup",
    "Get-CIDGroupMember",
    "Get-GroupRole",
    "Get-MemberCID",
    "Get-UserGroup",
    "Get-UserGroupMember",
    "New-CIDGroup",
    "New-UserGroup",
    "Remove-CIDGroup",
    "Remove-CIDGroupMember",
    "Remove-GroupRole",
    "Remove-UserGroup",
    "Remove-UserGroupMember",

    # oauth2
    'Request-Token',
    'Revoke-Token',

    # policy
    'Edit-DeviceControlPolicy',
    'Edit-FirewallPolicy',
    'Edit-IOAExclusion',
    'Edit-MLExclusion',
    'Edit-PreventionPolicy',
    'Edit-ResponsePolicy',
    'Edit-SensorUpdatePolicy',
    'Edit-SVExclusion',
    'Get-Build',
    'Get-DeviceControlPolicy',
    'Get-DeviceControlPolicyMember',
    'Get-FirewallPolicy',
    'Get-FirewallPolicyMember',
    'Get-IOAExclusion',
    'Get-MLExclusion',
    'Get-PreventionPolicy',
    'Get-PreventionPolicyMember',
    'Get-ResponsePolicy',
    'Get-ResponsePolicyMember'
    'Get-SensorUpdatePolicy',
    'Get-SensorUpdatePolicyMember',
    'Get-SVExclusion',
    'Get-UninstallToken',
    'Invoke-DeviceControlPolicyAction',
    'Invoke-FirewallPolicyAction',
    'Invoke-PreventionPolicyAction',
    'Invoke-ResponsePolicyAction',
    'Invoke-SensorUpdatePolicyAction',
    'New-DeviceControlPolicy',
    'New-FirewallPolicy',
    'New-MLExclusion',
    'New-PreventionPolicy',
    'New-ResponsePolicy',
    'New-SensorUpdatePolicy',
    'New-SVExclusion',
    'Remove-DeviceControlPolicy',
    'Remove-FirewallPolicy',
    'Remove-IOAExclusion',
    'Remove-MLExclusion',
    'Remove-PreventionPolicy',
    'Remove-ResponsePolicy',
    'Remove-SensorUpdatePolicy',
    'Remove-SVExclusion',
    'Set-DeviceControlPrecedence',
    'Set-FirewallPrecedence',
    'Set-PreventionPrecedence',
    'Set-ResponsePrecedence',
    'Set-SensorUpdatePrecedence',

    # processes
    'Get-Process',

    # real-time-response
    'Confirm-AdminCommand',
    'Confirm-Command',
    'Confirm-GetFile',
    'Confirm-ResponderCommand',
    'Edit-Script',
    'Get-PutFile',
    'Get-Script',
    'Get-Session',
    'Invoke-AdminCommand',
    'Invoke-BatchGet',
    'Invoke-Command',
    'Invoke-ResponderCommand',
    'Receive-GetFile',
    'Remove-Command',
    'Remove-GetFile',
    'Remove-PutFile',
    'Remove-Script',
    'Remove-Session',
    'Send-PutFile',
    'Send-Script',
    'Start-Session',
    'Update-Session',

    # samples
    'Get-Sample',
    'Receive-Sample',
    'Remove-Sample',
    'Send-Sample',

    # scanner
    'Get-QuickScan',
    'New-QuickScan',

    # scripts
    'Export-Report',
    'Find-Duplicate',
    'Get-Queue',
    'Invoke-Deploy',
    'Invoke-RTR',
    'Open-Stream',
    'Search-MalQueryHash',
    'Show-Map',
    'Show-Module',
    'Test-Token',

    # sensors
    'Get-CCID',
    'Get-Installer',
    'Get-Stream',
    'Receive-Installer',
    'Update-Stream',

    # settings
    'Edit-HorizonPolicy',
    'Edit-HorizonSchedule',
    'Get-HorizonPolicy',
    'Get-HorizonSchedule',

    # spotlight
    'Get-Remediation',
    'Get-Vulnerability',

    # user-roles
    'Add-Role',
    'Get-Role',
    'Remove-Role',

    # users
    'Edit-User',
    'Get-User',
    'New-User',
    'Remove-User'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry,
# use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry,
# use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData
# hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('CrowdStrike', 'Falcon', 'OAuth2', 'REST', 'API', 'PSEdition_Desktop', 'PSEdition_Core',
          'Windows', 'Linux', 'MacOS')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/CrowdStrike/psfalcon/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/crowdstrike/psfalcon'

        # A URL to an icon representing this module.
        IconUri = 'https://avatars.githubusercontent.com/u/54042976?s=400&u=789014ae9e1ec2204090e90711fa34dd93e5c4d1'

        # ReleaseNotes of this module.
        ReleaseNotes = "v2.0.7:
        General Changes
        * Added additional 'tags' to module manifest to help with PowerShell Gallery organization.
        * Added 'LicenseUri' to module manifest.
        * Added code to close file access methods when uploading files using 'Send' commands. Previously, if an
          upload failed and another attempt was made you would receive a notification that the file was
          already being accessed.
        * Added check during initial module load to enforce TLS 1.2 for connecting to CrowdStrike APIs.
        * Moved [System.Net.Http] check for PowerShell 5.1 from Invoke-Endpoint to base module load.
        * Updated base functions in an effort to improve error handling.
        * Added URI validation check to Invoke-Endpoint to improve error handling.

        Command and Parameter Changes
        * Re-wrote 'Get-FalconQueue' in an effort to increase performance when dealing with large numbers of
          results.
        * Fixed typo in 'Get-FalconIOARule' that was corrupting parameters and '-Help' output of the command.
        * Changed various 'verbose' outputs to 'debug' to reduce overall output when running with '-Verbose'. Some
          of the fields were not useful in a 'more information' context, but were for 'debugging'.
        * Updated the internal function 'Invoke-Loop' to automatically provide the '-Limit' parameter (at the
          maximum available value) when '-All' is specified with a command and '-Limit' was not included.
        * Added 'add-rule-group' and 'remove-rule-group' actions to 'Invoke-FalconPreventionPolicyAction' for
          assigning and removing Custom IOA Rule Groups from Prevention policies.
        * Removed 'Name' as a required parameter when using the 'Edit' policy commands as it should not be
          mandatory.
        * Updated 'Limit' for 'Get-FalconIOC' to 500 to match API.
        * Fixed 'Invoke-FalconHostGroupAction' to enable adding/removing multiple hosts at one time.
        * Added a 'pattern' value for 'Get-FalconUninstallToken' to make it clear that a device_id or the value
          'MAINTENANCE' can be supplied to retrieve an individual uninstall token or the more widely accepted
          maintenance token.
        * Added 'Array' parameter (used by 'Import-FalconConfig') to enable creation and modification of multiple
          items using a single request to the following commands:
            Edit-FalconDeviceControlPolicy
            Edit-FalconFirewallPolicy
            Edit-FalconHostGroup
            Edit-FalconPreventionPolicy
            Edit-FalconResponsePolicy
            Edit-FalconSensorUpdatePolicy
            New-FalconDeviceControlPolicy
            New-FalconFirewallPolicy
            New-FalconHostGroup
            New-FalconPreventionPolicy
            New-FalconResponsePolicy
            New-FalconSensorUpdatePolicy
        * Changed 'Settings' parameters for 'New-FalconDeviceControlPolicy', 'New-FalconResponsePolicy',
          'New-FalconSensorUpdatePolicy' and their matching 'Edit' commands to take a hashtable instead of an
          array to correct bug where policy creation/updates would fail.

        New Commands
        * Added 'Export-FalconConfig' and 'Import-FalconConfig' commands to export and import exclusions, policies
          and groups using an archive of Json files.
        * Added MSSP/Falcon Flight Control commands for new API endpoints:
          Add-FalconCIDGroupMember
          Add-FalconGroupRole
          Add-FalconUserGroupMember
          Edit-FalconCIDGroup
          Edit-FalconUserGroup
          Get-FalconCID
          Get-FalconCIDGroup
          Get-FalconCIDGroupMember
          Get-FalconGroupRole
          Get-FalconUserGroup
          Get-FalconUserGroupMember
          New-FalconCIDGroup
          New-FalconUserGroup
          Remove-FalconCIDGroup
          Remove-FalconCIDGroupMember
          Remove-FalconGroupRole
          Remove-FalconUserGroup
          Remove-FalconUserGroupMember

        GitHub Issues
        * Issue #13: Creating/modifying multiple objects in one request handled with new 'Array' parameter
          for commands used with 'Import-FalconConfig'.
        * Issue #31: Added code to the 'Get-Body' function to .Normalize() text grabbed with 'Get-Content' and
          prevent errors when the content is converted to Json for API submission.
        * Issue #33: Changed default permission level for 'runscript' command to Admin when using
          'Invoke-FalconRTR' to compensate for '-Raw' parameter not working with Active Responder permissions.
        * Issue #34: Added 'Test-FalconToken' command to display token status and additional client information
          including 'ClientId', 'Hostname' and 'MemberCid'. Also made various changes to improve general error
          message production.
        * Issue #36: Set 'Limit' maximum to 500 for 'Get-FalconIOAExclusion', 'Get-FalconMLExclusion', and
          'Get-FalconSVExclusion'.
        * Issue #43: Updated 'ids' and 'value' parameters to correct bugs related to 'Invoke-FalconIncidentAction'.
        "
    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/crowdstrike/psfalcon/blob/master/README.md'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix
DefaultCommandPrefix = 'Falcon'

}